Fix failing test where code fails to wait for promise to resolve
Fixes the following test failure:

  1) NoResponse
       unmark
         when perform is set to true
           when the issue does NOT have the response required label and the commenter is the issue author
             does not alter the issue:
     Error: spy was not supposed to be called
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toNotHaveBeenCalled (node_modules/expect/lib/Expectation.js:346:28)
      at Context.<anonymous> (test/no-response-test.js:331:45)